/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArrowDown: typeof import('./src/components/icons/ArrowDown.vue')['default']
    ArrowsRightLeft: typeof import('./src/components/icons/ArrowsRightLeft.vue')['default']
    Backward: typeof import('./src/components/icons/Backward.vue')['default']
    Bars: typeof import('./src/components/icons/Bars.vue')['default']
    ChevronDown: typeof import('./src/components/icons/ChevronDown.vue')['default']
    Dvd: typeof import('./src/components/icons/Dvd.vue')['default']
    DvdPointer: typeof import('./src/components/icons/DvdPointer.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    EllipsisVertical: typeof import('./src/components/icons/EllipsisVertical.vue')['default']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Event: typeof import('./src/components/common/Event.vue')['default']
    Forward: typeof import('./src/components/icons/Forward.vue')['default']
    FullContainer: typeof import('./src/components/common/FullContainer.vue')['default']
    FullHalfContainer: typeof import('./src/components/common/FullHalfContainer.vue')['default']
    Heart: typeof import('./src/components/icons/Heart.vue')['default']
    Icons: typeof import('./src/components/icons/index.vue')['default']
    ListContainer: typeof import('./src/components/common/ListContainer.vue')['default']
    Loading: typeof import('./src/components/global/Loading.vue')['default']
    Message: typeof import('./src/components/icons/Message.vue')['default']
    MusicalNote: typeof import('./src/components/icons/MusicalNote.vue')['default']
    NeteaseCloudMusic: typeof import('./src/components/icons/NeteaseCloudMusic.vue')['default']
    Pause: typeof import('./src/components/icons/Pause.vue')['default']
    PauseCircle: typeof import('./src/components/icons/PauseCircle.vue')['default']
    Play: typeof import('./src/components/icons/Play.vue')['default']
    PlayCircle: typeof import('./src/components/icons/PlayCircle.vue')['default']
    PlayPause: typeof import('./src/components/icons/PlayPause.vue')['default']
    Radio: typeof import('./src/components/icons/Radio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Share: typeof import('./src/components/icons/Share.vue')['default']
    SongList: typeof import('./src/components/common/SongList.vue')['default']
    SongMore: typeof import('./src/components/common/SongMore.vue')['default']
    SongTrack: typeof import('./src/components/common/SongTrack.vue')['default']
    SpeakerWave: typeof import('./src/components/icons/SpeakerWave.vue')['default']
    SubContainer: typeof import('./src/components/global/SubContainer.vue')['default']
    SubLink: typeof import('./src/components/global/SubLink.vue')['default']
    SubView: typeof import('./src/components/global/SubView.vue')['default']
    TabPage: typeof import('./src/components/common/TabPage.vue')['default']
    User: typeof import('./src/components/icons/User.vue')['default']
    UserGroup: typeof import('./src/components/icons/UserGroup.vue')['default']
    VideoCamera: typeof import('./src/components/icons/VideoCamera.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
